### ISSUE TITLE
ranktoken

### ISSUE THREAD

**Issue by SeyyedHesamMirebrahimi** [riedayme/InstagramKit#2]
i found that u use an static rank token for search tags and users 
i had mgp25/instagram-api and it was used this funtion to generate rank tokens 
    public static function generateUUID(
        $keepDashes = true)
    {
        $uuid = sprintf(
            '%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0x0fff) | 0x4000,
            mt_rand(0, 0x3fff) | 0x8000,
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff),
            mt_rand(0, 0xffff)
        );

        return $keepDashes ? $uuid : str_replace('-', '', $uuid);
    }

**Comment by riedayme** [comment]
oh of course all of this scripts I learned from mgp25

so there will definitely be something in common
